### ISSUE TITLE
合匪法的土特产

### ISSUE THREAD

**Issue by marschvor** [fanhan-inside/fanhan-inside.github.io#242]
https://www.sohu.com/a/278434664_120014491
> 烫圪旦是吸毒！内蒙警方查处多起安钠咖案件，多人被刑拘

> 现场缴获固体安钠咖2715.67克、液体安钠咖23500毫升、**干罂粟壳115.56克、湿罂粟壳176.39克**以及部分熬制加工安钠咖的工具

> 目前，刘某某夫妇因涉嫌贩卖毒品安钠咖被达旗公安局依法刑事拘留，黄某、张某某因涉嫌吸食安钠咖被依法行政拘留2日

晋绥地区吸贩制毒在当地已经是处于一种的合法的状态，上面案件中的所谓“安钠咖”已经是包含鸦片了，但吸贩制的此几人也关不了几天就能出来。如其说是作案被抓，不如说分赃不均，罚酒三杯，或者是新警察初来乍到坏人好事，为善。
上面的安钠咖，圪旦以及之前提及的片片，可见只是对在共匪或共匪友好势力控制下的毒品贩卖特有称呼。https://susong.tianyancha.com/c1c74a471cbb11e6b554008cfae40dc0
这里面有类似案件具体文书

**Comment by fanhan-inside** [comment]
非常感谢提供情报

**Comment by fanhan-inside** [comment]
补充情报：

![](https://user-images.githubusercontent.com/41445691/179347916-6f812d35-534d-4d8f-8355-f18fceb0ec4e.png)

前情提要：

+ [《范版东幻异闻录》题外话〔21〕低女权国家培训燕子，在高人权兲朝广钓舔狗](https://fanhan-inside.bitbucket.io/fantasy/bizarre/000/000-021.html)

> 或问了，日本传统风俗习惯都知道，哪儿来的女权主义者？正因为在日本没有立足之地才会在中国扎根吖。本朝第一部成文法就是《婚姻法》，啥事都不干先保证女性权益，所以那些传统上女性地位低的国家和地区，都纷纷派遣女细作混进兲朝来了。沙特认定女人是哺乳动物的同时还暗地里掏钱赞助女权主义也不是国家机密兼宇宙奥秘，罗刹人喝多了就打老婆的同时还到处炫耀酒桶状大妈武德充沛也不是国家机密兼宇宙奥秘。只要希伯来太君让阿拉伯太君出钱买通兲朝人大代表全票通过女权主义法，这帮雌性间谍特务卧底就特么全来了，女侠们各自钓舔狗打了几十年代理人战争。

>
> 参考国际一流和谐宜居之都「高学历精英社交圈」爆料：《[舔狗们发现自己舔的女神在原籍是当地军警宪特的肉便器是种怎样的体验？](https://www.zhihu.com/question/307189774)》

>
> 以及南直隶「远东第一体育论坛」爆料：《[舔狗中的战斗机：发现自己舔的女神与境外大手情报机构负责人联系时撒娇卖嗲百般跪舔，心态崩了](https://bbs.hupu.com/35929507.html)》

>
> 这些指桑骂槐的爆料，都证明了境内无处不在的励志故事「从女奴到女王」：先低头翘腚接受境外大手情报机构的培训，出师后来兲朝昂首挺胸广钓舔狗，即可加冕新时代王冠。

**Comment by fanhan-inside** [comment]
补充情报：

![](https://user-images.githubusercontent.com/41445691/179861939-d848bb52-a3fd-45a0-a505-55b7383667f7.png)

没有调查就没有发言权，我虽然既没去过美国也没去过新疆，但是家贼送货上门会提供大批与新疆生产建设兵团有关的情报，应该是当年陕北三五九旅供销社卓越的领导人王震去新疆推广晋绥陕甘宁特货销售成功经验的人脉缘故。

就说2021年1月5日家贼上门找我要了×××××元货款，第二天送来三罐「天山雪蜜」作为货物，均价××××元一罐，四位数人民币。家贼特意叮嘱，可以「抹在面包片上吃」，等于还有其它附加款项。新疆的物价由此可见。

至于为什么非得是「面包片」，可以与之后「当你只想要一块面包的时候，老板认为你不值一块面包」，以及家贼特意送面包上门的动向结合起来。按说新疆种小麦也是拉条子烤馕，面包并不多，除了生活习惯完全「欧（含罗刹）美化」的部分殖民者之外。

再往后就是××××元货款换六罐山东出产的清真罐头，均价三位数人民币一罐，也挺贵，绝大部分都是「清真税」，但比新疆物价便宜多了。

怎么说呢，还是那句话，正如金三角、金新月以及拉丁美洲部分地区，除了毒品便宜之外，什么都贵。

**Comment by fanhan-inside** [comment]
严密的考虑问题，还有可能是物流成本。

简单说，「天山雪蜜」就是超市里面常见的玻璃瓶装那种榨菜了辣椒了芝麻酱了，200-300克，从新疆运到北京，三四千元一罐。而「清真罐头」也是超市里常见的扁圆形金枪鱼了火腿了，差不多200-300克，从山东运到北京，七百五十元一听。

然后就是去年五月多吧，家贼找我要七万块钱「交供暖费」，理由过于奇葩并且数额明显过于嚣张跋扈（此处修辞正确），就不同意。今年六月三十日，接到北京燃气电话说供暖费每年「只要一千一百多块钱」。

那么问题就来了：**去年中国境内又没打内战，难道「西气东送」管道由于涡轮机维修被截断了么？**
