### ISSUE TITLE
晋绥的乔某土特产卡特尔

### ISSUE THREAD

**Issue by marschvor** [fanhan-inside/fanhan-inside.github.io#243]
只要查询晋绥地区的贩毒案件，就大概率有乔某和乔某某在其中。
目前我看到存在乔某的判例里刑期还没有超过一年的

**Comment by fanhan-inside** [comment]
非常感谢提供情报。与个人亲身经历的第一手材料可以互相对照。

**Comment by fanhan-inside** [comment]
补充情报兼素材：

![](https://user-images.githubusercontent.com/41445691/179337102-ed1acac4-e729-4972-8a88-08db8a269ee4.png)

个人亲身经历的第一手材料（之前的谈笑风生当中写过，懒得找链接）：

+ “儿砸！爹带你去大绿门派出所换身份证！”
+ “还有四年才到期现在急个啥？”
+ “银行柜台窗口让换的。”
+ “不按照户口就近去古拉格北里派出所，大老远跑去大绿门作甚？”
+ “不知道，银行就这么说的。”

相关剧情：

> “再懒也得动手了吧？”茨维特科看着范翗翷终于站起来了，往夹好碎肉和生菜的面饼里挤酱汁，“魔法不是万能的”。
>
> “划不来而已”，范翗翷早知道茨维特科也知道计算成本收益，类似的对话好多次了，每一次都乐此不疲，“这道菜叫什么来着？”
>
> “<ruby>尅八部<rt>kebab</rt></ruby>”，茨维特科也有默契，配合范翗翷旁若无人的故意说给旁人听。
>
> “各位久等了”，范翗翷挥手，一堆盘子飞过去各就各位，“欢迎品尝本店特色料理，<ruby>卡舒吉<rt>Khashoggi</rt></ruby>”。
>
> 白袍脸色变了。
>
> ——[《范版西幻设定集》之二十〈新长征路上的摇滚〉](https://fanhan-inside.bitbucket.io/fantasy/fanism/020.html)

> “哎，你咋这么说话？”格维终于发现不对劲了，“今天高兴，请你喝一顿，咋这么不给面子呢？”
> 
> “昨天你不高兴了，也扯着我喝酒”，瓜维说，“你咋从来也不问我高兴不高兴呢？”
> 
> “你到底咋了？”格维发现瓜维确实是心情不好，并不是平时打趣拆台那种表现。
> 
> “估计和你今天心情好之间存在着统计上的相关性”，瓜维说，“昨天晚上我爹来找我了，说要带我去对岸<ruby>凯尔<rt>Kehl</rt></ruby>派出所换身份证”。
> 
> “你的户口不是早就迁过来了么？”格维和瓜维是老邻居，也是同行，虽然不在同一个教区上班，但平时下班之后经常相约酗酒吹牛哔，对于对方的情况大概有些了解，“要搬家了？”
> 
> “不知道吖，问就是别的啥事也没有”，瓜维说，“我说‘还有四年才到期呢现在急个啥’，就说<ruby>莱茵河航运中央委员会<rt>Zentralkommission für die Rheinschifffahrt</rt></ruby>窗口让换的’，再问就啥也不说了”。
>
> ——[《范版西幻设定集》第二辑草稿〈一条大河波浪宽〉（原名〈碧眼小儿紫髯鼠辈〉）](https://fanhan-inside.bitbucket.io/fantasy/fanism/v02_draft/v02-006.html)

**Comment by fanhan-inside** [comment]
补充情报兼素材：

![](https://user-images.githubusercontent.com/41445691/179400240-775b419c-6fe7-471a-af6f-99213e07cf88.png)
![](https://user-images.githubusercontent.com/41445691/179400243-9445aef6-42e5-495e-92ad-5d9fa1961fa9.jpg)
![](https://user-images.githubusercontent.com/41445691/179400244-9c7442fe-e773-485e-bc91-12dbd2b5442a.jpg)
![](https://user-images.githubusercontent.com/41445691/179400246-afc4333c-7dff-4221-8b46-30c33e3fb1f7.jpg)

另外，看疑似高衙内家帮闲的那帮「竞技爱好者」忽然开始翻旧账曰若稽古，估计继「<ruby>神户<rt>KOBE</rt></ruby>」与疫情期间驾驶直升机摔死之后，「<ruby>约旦<rt>Jordan</rt></ruby>」也该在最近的中东乱局当中出点啥事了。
