### ISSUE TITLE
今年年初在知乎和色目回回恶斗一番。

### ISSUE THREAD

**Issue by TianMo-ZhangSan** [fanhan-inside/fanhan-inside.github.io#244]
发现开封色目人在历史中可能起到很大因素。
至少知道开封，金陵，大都都有大量活跃痕迹。
现在河南出了这么多金融创新，我看还是这批色目搞鬼。而且网上有人联系到南京也有一批金融人才在搞。我看大都的创新也必须有。

**Comment by TianMo-ZhangSan** [comment]
河南山东南京都有特大型色目研究所

**Comment by TianMo-ZhangSan** [comment]
南京研究生课程有，关于中国网络反油主义的研究。

**Comment by TianMo-ZhangSan** [comment]
大明说不定还是亡于色目人？按恶斗时某些色目贵种自爆，操纵四等含历史进程至少大宋起

**Comment by TianMo-ZhangSan** [comment]
开封色目七大祠堂，也有张，赵。

**Comment by fanhan-inside** [comment]
非常感谢提供情报。

北宋开封色目人自称希伯来太君，而大萌金陵色目人则是穆斯林，精通阿拉伯语和波斯语，以儒解经建立「金陵学派」传承至今，陈独秀就是这个「名门正派」出身的职业神棍。

**Comment by TianMo-ZhangSan** [comment]
按色目官方地方志记载开封色目改宗穆斯林的不少，我看这是同一批人在不同地方的扩散。身份是潜伏任务决定的。恶斗的色目贵种在三地都有关系。

范狂夫 ***@***.***> 于 2022年7月15日周五 上午6:53写道：

**Comment by fanhan-inside** [comment]
最典型的例子就是张承志，「北京特产血脖子红卫兵」，与陈独秀从「傻哔绿人」摇身一变为「牛哔红人」如出一辙。

哲合忍耶是从内亚「一带」传播到北京的，与当年沿海「一路」传播到南京的金陵学派那帮人没有本质区别，都是接受了组织交代的革命任务，坚决贯彻落实方针政策路线计划并完成，包括但不限于以「骆驼奶」「蚕丝被」之类借口搞传销众筹集资诈骗替邪教敛财，死到临头了还能偷走目标手机之类。

在 2022/7/15 9:01, Zhangsan 写道:
> 按色目官方地方志记载开封色目改宗穆斯林的不少，我看这是同一批人在不同地方的扩散。身份是潜伏任务决定的。恶斗的色目贵种在三地都有关系。 
>

**Comment by fanhan-inside** [comment]
补充情报：

![](https://user-images.githubusercontent.com/41445691/179325376-0565f66c-1aca-4625-b858-03aba5ee3ed3.png)

以前提到过，古拉格北里社区「军休所」当中经常出没哥布林，还有大批红二三四代军二三四代「望之不似人民子弟兵」。

由于社区之外不远就是「山西大厦」或曰「并州驻京办事处总部」，所以才会根据哥布林活动轨迹查询历史档案获得《晋绥陕甘宁边区特货问题研究》这种资料，然后被色目心理学家鉴定为「患上了“看谁都是毒贩”的受迫害妄想狂综合征」。

当时就提出一个尖锐的问题：**这帮离退休鲜卑名将之花到底是「共军」还是「国军」？**

但是没有获得任何回答。

现在看来，应该是「侵华日军」才对。
