### ISSUE TITLE
知乎发现几个liu姓太君，没想到是皈依犹 教的希伯来太君。

### ISSUE THREAD

**Issue by TianMo-ZhangSan** [fanhan-inside/fanhan-inside.github.io#42]
我们会看见惊天动地的事。

**Comment by fanhan-inside** [comment]
刚注意到，本站迄今为止唯一的「Fork」看帐号也应该是「**liu**」某。

**Comment by fanhan-inside** [comment]
简单说砥砺奋进七八年来的「大目标」就是「**蒙古治世**（_Pax Mongolica_）」的翻版，正如上一次蒙古太君武德充沛兲命昭昭的背后有色目太君伪装成「商界精英」到处渗透负责刮地皮搜集情报保障后勤一样，这次也差不多，如果没有外援撑腰那些「吃沙子喝西北风的穷哔」（伪装成皇汉的色目情报掮客语）不可能席卷兲下。

热兵器出现以后就不是控弦十万就能转进如风的时代了，没有根据地保障物资供应，吹上天的「钢铁洪流」都是与时俱进的「流寇」而已。撑死了按照肃慎情报掮客炫耀兵不厌诈那样，「傻了吧爷会飞，蝗虫吃光了当然就跑路了，难道还留下来帮费拉种地不成？」这种「一带一路」战略或曰伪装成苏修的哥萨克游盗集团四时捺钵体制。

于是「坚决打击大汉族主义」的野望遭到尼堪强烈反抗之后，宣传口径变成「**中华治世**（_Pax Sinica_）」了，言必称「中华民族传统文化」其实就是汉族精华和少数民族糟粕的混合体，一帮紧密团结在以杀伐果断通权达变狠角色为核心的肃慎中央周围的色目混混鸡鸣狗盗之徒，在「紫气东来」「西天取经」「风从草原来」纠集充沛的索虏之后，准备打过长江去解放岛夷呢。

按照如意算盘一桶浆糊之后，就是境内法西斯化再对外「输出革命」，可以参考上世纪六十年代。

**Comment by Gullinkambi07** [comment]
啊 这~
本费拉感觉十分惶恐

**Comment by fanhan-inside** [comment]
> 啊 这~
> 本费拉感觉十分惶恐

现在更新到「英国皇上与美国寡妇」了，按照色目文艺爱好者叫嚣「<del>没什么自由意志，军情六处已经钦定了</del><ins>作者最大剧本钦定导演叫人三更死谁敢留人到五更</ins>」，翻拍划时代经典大作的所有因素差不多都凑齐了。

简单说，不惮以最大的恶意揣测，白金汉宫老佛爷恐怕有不忍言之事，然后查理三世登基后爆料卡米拉乃克格勃特务被中央情报局策反，于是查理三世退位去加拿大管理冰球俱乐部，威廉五世登基，把爹封为第二代温莎公爵……第三次世界大战开场。

**Comment by fanhan-inside** [comment]
> 我们会看见惊天动地的事。

耍钱的<ruby>新浪<rt lang="ja">シナ</rt></ruby>或曰后浪正在奔走相告的色目含量爆表的重要情报：

> 15:21:14&emsp;距以色列电视台高级记者：以色列总理内塔尼亚胡在周日秘密访问了沙特阿拉伯。
> 
> 15:29:25&emsp;据以色列军队广播：以色列总理内塔尼亚胡周日在沙特会见了沙特王室王子和美国国务卿蓬佩奥。
> 
> 22:25:36【阿联酋宣布开放市场新举措 12月1日起外商可100%持股当地企业】当地时间11月23日，阿联酋总统谢赫哈利法·本·扎耶德·阿勒纳哈扬签署了修订的《阿联酋商业公司法》，从2020年12月1日起，取消对外国投资者在当地注册公司的持股比例限制。此举被认为是阿联酋市场开放的重大举措，对于在中东经营的中资企业也是一项利好。
> 
> 23:01:54&emsp;市场消息：谷歌据悉计划在沙特与以色列间建设光纤网络。

你说的是不是就是这件事？

之前市面上色目情报掮客正在对赌，兲朝和罗刹谁先解体，兲朝和欧盟谁先崩溃，迄今为止仍然游离于世界金融体系之外的兲朝银行系统和阿拉伯银行系统谁先无条件投降。

现在看来，砥砺奋进八年来有大批隐姓埋名人干惊天动地事，但是蚂蚁金服暴雷未果，兲朝暂时躲过一劫，于是就轮到「绿色金融」开放的大门越开越大了。

**Comment by TianMo-ZhangSan** [comment]
其实我只是感慨世事难料。
不清楚金融业事情。
各种技术工程进度太快了！
谷歌停止图片无限储存服务。人工智障需要的数据估计够了。
各种取代工人的技术在现在的背景下真正在演化了！

**Comment by TianMo-ZhangSan** [comment]
阿拉伯人估计被色目人渗透成筛子了！这些都只是转变成明面上了。什么和平进程，外交突破都只是表现控制力而已。
看情况，哎苏丹土耳其是甘愿做棋子了。

**Comment by TianMo-ZhangSan** [comment]
各种武德远人都会重新包装起来。

**Comment by fanhan-inside** [comment]
> 其实我只是感慨世事难料。
> 不清楚金融业事情。
> 各种技术工程进度太快了！
> 谷歌停止图片无限储存服务。人工智障需要的数据估计够了。
> 各种取代工人的技术在现在的背景下真正在演化了！

当初在之江临安「原创文学论坛」连载第四篇设定时中断的原因，就是有大批自诩始终代表了最先进生产力的高学历精英搅局，我引用其它权威的结论回答「科技进步会使人类生活更便利，但不会使人民群众更幸福」就被追着喷。

我当然还是对喷，调整任务优先级，政治和意识形态斗争本身优先于码字，反过来追着它们喷，色目情报掮客出现在哪里，我就喷到哪里，一直喷到党性坚定的老审查员出场将我在各个宣传阵地当中的帐号以「政治敏感」理由「亦当删去」为止。

到现在了，各种「技术奇点」导致的后果都展现出来了，色目情报掮客开始从「有錢是真的能為所欲為的.gif」转进为「傻了吧，爷会飞」「凭本事骗来的钱，凭什么要还」「皇虫吃光庄稼当然跑路，难道还会留下来帮两脚畜牲种地不成」，恕不再壹壹列举。

顺便，就事论事，最近市面上「文艺理论」相关指桑骂槐当中提到「不会写反派」并顺便吹捧个谁。之所以判断是指桑骂槐，是因为这帮到处炒作的情报掮客与当初追着我喷的是同一批人。所以开始汇总反派相关线索了嘛，从我的视角看来这帮喷子就是反派。它们吹什么，什么就是反派；它们吹谁，谁就是幕后黑手。

今后同样，只要这帮情报掮客还在活蹦乱跳，总得对得起工资。于是可供搜集的素材极大充沛，反派的形象会越来也丰满。敬请期待。

**Comment by fanhan-inside** [comment]
> 阿拉伯人估计被色目人渗透成筛子了！这些都只是转变成明面上了。什么和平进程，外交突破都只是表现控制力而已。 看情况，哎苏丹土耳其是甘愿做棋子了。

本来就是，我一直强调「色目人是同一伙扮红白脸唱双簧」，有娱乐至死の色目逗哔用《星际争霸》剧情放风带节奏。砥砺奋进八年来色目情报掮客叫嚣「西天取经是政治任务」「没什么自由意志，中央情报局已经钦定了」就没消停过，局势发展到现在，已经图穷匕见了吖。

所以我说这帮喷子是幕后黑手集中统一领导下的反派外围炮灰，无一字无来历。

**Comment by fanhan-inside** [comment]
> 各种武德远人都会重新包装起来。

刚才直接回复邮件，发现不能自动显示在这里。

简单说，就看繁荣的简体中文互联网上热烈讨论第三次世界大战，也知道「战后秩序」也就是所谓联合国五常体制，已经被惦记着抢班夺权的童年才俊视为「万恶的旧社会」了，伴随本次全球遭瘟而建立的「百善の新时代」，当前蠢蠢欲动的「里世界五常」之活跃，与一战二战之前的世界局势完全一样。

而睁眼说瞎话叫嚣「兲朝经济稳中向好，国际局势和平的一哔」才是烟幕弹障眼法麻醉剂，或曰战略欺骗。

**Comment by TianMo-ZhangSan** [comment]
https://mashable.com/article/pine-mountain-atascadero-monolith/

Utah monolith犹他州开始的宗教石碑。色目人就这种德行，改不了鬼鬼祟祟的习惯。

**Comment by fanhan-inside** [comment]
> https://mashable.com/article/pine-mountain-atascadero-monolith/
>
> Utah monolith犹他州开始的宗教石碑。色目人就这种德行，改不了鬼鬼祟祟的习惯。

老迈年高的读者认为是《2001：太空漫游》的典故，只不过原版是「黑石」，据称是<ruby>黑石集团<rt lang=“en”>The blackstone group</rt></ruby>或<ruby>黑岩集团<rt lang="en">BlackRock, Inc.</rt></ruby>在「奋六世之余烈」期间提前打广告的行动之一。现在可能已经羽翼丰满，准备「吞二周而亡诸侯」了。

顺便，《2012》玛雅预言也是一样，再早就是1999诺查丹玛斯预言，这都是指定了时间点，其它制片人不配合，所以没闹起来。再晚就是《教宗预言》，也到了最后一幕了。总而言之，色目人朝思暮想的「<ruby>第三圣殿<rt lang="de">Das Dritte Reich</rt></ruby>」，总得找个炒作热点，搅合得天下大乱才容易混水摸鱼。
