### ISSUE TITLE
关于“土特产”2014年左右有一篇很详尽的文章

### ISSUE THREAD

**Issue by marschvor** [fanhan-inside/fanhan-inside.github.io#43]
https://www.newsmth.net/nForum/#!article/Modern_CHN/430727

**Comment by fanhan-inside** [comment]
非常感谢，印象里多年前看到的素材当中就有结尾的那段：

> 最后以萧军的一句话结束全篇，这是他听南汉宸报告边区制作鸦片烟膏后的一句感悟：
>
> “革命的花是从最卑污的粪壤里开出来的。”

当时印象深刻，但是一时找不到出处。

所以在第十四篇设定《食不厌精脍不厌细》的结尾用了类似的表达方式：

> “你知道你吃进肚子里的粮食蔬菜水果，都是用屎尿培育才会茁壮成长的么？”明斯克反问乌呼鲁。
>
> “我知道你来干什么了”，斯米尔诺夫指着明斯克。
>
> “我也知道了”，菲利克斯说。
