### ISSUE TITLE
对于这次疫病有一种说法

### ISSUE THREAD

**Issue by marschvor** [fanhan-inside/fanhan-inside.github.io#44]
![A](https://user-images.githubusercontent.com/68501880/89501029-3b4bbc80-d7f5-11ea-81c3-43d751c2a59b.png)
微博在一月末有很多大讨论，煮老师徐波实名举报病毒研究所，直接被去迹删号了。当时讨论披露了很多消息，大体是这个病毒的研究之前都在欧美进行，2018年左右却转移到中国来了。

**Comment by fanhan-inside** [comment]
非常感谢。

这种情报在墙内即便发出来也会秒删，我看到的多半是消息灵通人士兼娱乐至死の逗哔的影射。

包括但不限于《星际争霸》版色目钦定大目标，《启示录》版色目钦定大目标，以及希腊神话版《封神演义》，说足协主席竞选军委主席但票数落后，输急眼了就惦记着「重开洪荒」然后被国际奥委会拎走了。
