### ISSUE TITLE
晋绥地区制“土特产”的行为一直就没有中断过

### ISSUE THREAD

**Issue by marschvor** [fanhan-inside/fanhan-inside.github.io#45]
https://zhuanlan.zhihu.com/p/56103115

疯狂绅士 回复Sunshuaijie 2019-02-02
不是的哟，其实山西的溜冰是很有特色的，起源跟广东的不同的。

80年代山西就有这个玩意，80年代末就央视就排了纪录片的。

当时的主要是掺入鸦片。到后来山西的主要是掺入土冰。而内蒙是我国麻黄草的主要产地。山西是土法制毒，所以叫土冰，广东制毒村用的麻黄草还是内蒙山西等地方的。

----------------------------------------------------------------
`某组织打KMT这么厉害，情报优势那么大，“无人不通X”，看来只是掌控了全国贩毒网络而已。毒贩本来就和情报掮客是一体两面的。中国的贩毒网络是犹太人构建的，某组织是怎么达成交易的呢？`

**Comment by fanhan-inside** [comment]
非常感谢。

刚才在其它地方看见了陕甘宁边区的「统战」工作：

> 1940年3月31日，中国共产党在延安成立了“蒙古文化促进会”，4月，在延安建立了“成吉思汗纪念堂”和“蒙古文化陈列馆”，敬立成吉思汗半身塑像，并由毛泽东题写了“成吉思汗纪念堂”七个大字。在这里每年农历三月二十一日，也就是成吉思汗春季查干苏鲁克大祭之日，延安各界举行盛大的祭奠仪式，以蒙汉两种语言诵读成吉思汗祭文。1942年5月5日，蒙古文化促进会还编辑出版了《延安各界纪念成吉思汗专刊》。毛泽东和朱德分别为专刊题词，内容如下：
> + 毛泽东题词：团结抗战
> + 朱德题词：中华民族英雄

顺便，根据回忆，我的户口本假亲戚的人脉分布范围，还就是「晋绥边区」的临界点，阳曲、大同、归绥、包头，都曾经来京「省亲」过，没一个给我好脸色看，估计当年肯定和本职毒贩兼职情报掮客的「通匪」经历脱不开关系。

按照追着我喷「孤儿」的那帮根红苗正忠君爱国童年才俊的嚣张气焰不惮以最大的恶意揣测，可能我的唯物主义亲属都已经牺牲在缉毒第一线了，然后在香港豢养查博导或在台湾豢养熊文豪的汇丰等贩毒幕后黑手为了啥「亲痛仇快」「造化弄人」的文艺理论，才安排了「狗杂种」「傅红雪」之类屡试不爽的套路。

**Comment by TianMo-ZhangSan** [comment]
这个远古情报，还有色目人参与。大清时期，开封色目重新接头昂撒人毒贩老乡。
