### ISSUE TITLE
把「宾夕法尼亚」翻译成「潘家园」，以及其它地名本土化

### ISSUE THREAD

**Issue by fanhan-inside** [fanhan-inside/fanhan-inside.github.io#46]
简单说，这个地点在《设定集》《异闻录》当中都会出现，还是重大事件发生的场所，因此决定慎重的字斟句酌。

***

摘抄维基百科的介绍：

> 宾夕法尼亚州是美国的州份之一，正式名称为“宾夕法尼亚邦”（英语：Commonwealth of Pennsylvania），俗称“拱心石州”（英语：Keystone State），中文简称宾州。这个州的名称起源于英国移民威廉·宾，英国国王查理二世为偿还其父亲的债务而授予大片林地，**拉丁文中的意思是“宾的林地”**。

所以翻译成「潘家园共荣圈」，简称「潘家园」。

> 威廉·佩恩（William Penn，1644年10月14日－1718年7月30日）是十七世纪的一名著名英国拓荒者及作家，开拓了以其命名的宾夕法尼亚州及为其首府费城的奠基者。出身于航海及贵族世家，为英国皇家海军上将及国会议员老威廉·佩恩爵士之子，亦为虔诚的基督新教贵格会信徒--是英国首批自由主义与民主支持者，同时也支持宗教自由。
>
> 其中，最著名的事迹为开拓了以同本名来命名的宾夕法尼亚州。1681年，英国国王查理二世御赐一片幅员广阔的北美土地，以代偿还威廉·佩恩所欠下老威廉·佩恩（父亲）的积薪，面积涵盖现今的的宾夕法尼亚州及特拉华州，并于原住民特拉华族成功签订条约并建立稳定外交关系，在当地发展殖民地后亦奠基了费城，成为了整个殖民地的首府，以及当时北美殖民地最具规模的都市。

所以翻译成「潘」，尤其是《设定集》当中，可以引用大批素材以充沛其架空家族，包括但不限于「潘安」「潘仁美」以及「潘金莲」，当然还有著名台词「大郎，该吃药了」。

> 费城（Philadelphia），即费拉德尔菲亚，也常被简称为菲利（英语：Philly）。**「费拉」即希腊文“友爱”的意思**，是传教士命名的。

正在考虑翻译为「朋城」，或者「上党郡」，还在推敲当中。

> 匹兹堡（Pittsburgh）位于美国宾夕法尼亚州西南部，阿勒格尼河与莫农加希拉河汇合成俄亥俄河的河口。17世纪后期欧洲殖民者建立了毛皮贸易站。18世纪中叶，法国殖民者在此建立据点迪尤肯堡。1758年为英国殖民者夺取，**以英国首相威廉·皮特，第一代查塔姆伯爵（William Pitt）命名**该市。1816年与附近一些移民点合并。1837年宾夕法尼亚运河建成，1851年铁路通达，该地成为重要的水陆交通枢纽。

已经翻译为「皮中堂堡」了，本来想简化为「皮相堡」，但是这位是首相，不是国际象棋的相（主教），为避免歧义暂时不变。

***

不知各位读者有什么意见？

**Comment by Akatasch** [comment]
还~行·~
