### ISSUE TITLE
把《范版东幻异闻录》的正式名称定为《邦昌时代》怎么样？

### ISSUE THREAD

**Issue by fanhan-inside** [fanhan-inside/fanhan-inside.github.io#47]
参考先例，个人博客上传的第一篇文章「[划时代长篇科幻巨著の大纲](https://fanhan-inside.github.io/essay/advancing/001.html)」就运用了码农惯例安排了三个名称。

- 内部代号：《魔法低材生研究奥术收编那些女巫终于登上神座》
- 正式名称：《<ruby>觋<rt>xí</rt></ruby><ruby>铪<rt>há</rt></ruby>演义》（«A Tale of Hip-Hop»）
- 俗名别称：《<ruby>董<rt>Don</rt>吉诃德<rt>Quijote</rt></ruby>》

同理可证，《范版东幻异闻录》本来是面对砥砺奋进七八年来乃至更早一段时间铺天盖地追着我狂喷的擅长东方传统题材的钦定文豪码字巨侠之粉丝的造谣污蔑栽赃陷害，决定「示范」如何瞎编乱造炮制划时代大作的过程。一路「只胡乱做将去」到了现在似乎有那么一丁点「水到渠成」的苗头了，于是决定起个正式名称。

毕竟自称始终代表了中华民族传统文化的山东曲阜殷商余孽教导我们说「名不正则言不顺；言不顺则事不成；事不成则礼乐不兴；礼乐不兴则刑罚不中；刑罚不中则民无所措手足」然后眼瞅着一个馒头不仅引发了血案还会引发第三次鸦片战争兼第三次世界大战了嘛～～～

当然，简介也要按照业内行规抄袭剽窃借鉴企图复制并成功：

> 这是最好的时代，这是最坏的时代；这是智慧的时代，这是愚蠢的时代；这是信仰的时期，这是怀疑的时期；这是光明的季节，这是黑暗的季节；这是希望之春，这是失望之冬；人们面前有着各样事物，人们面前一无所有；人们正在直登天堂，人们正在直下地狱。

不知各位读者意见如何？

**Comment by CESTBON5146** [comment]
github博客打不开
源码能看是能看，但是看着不舒服

**Comment by fanhan-inside** [comment]
> github博客打不开
> 源码能看是能看，但是看着不舒服

博客站点应该被墙了。
源码在线看当然不舒服，可以用git把整个站点clone到本地看，每次更新就像其它项目远程协作那样。

**Comment by CESTBON5146** [comment]
> > github博客打不开
> > 源码能看是能看，但是看着不舒服
> 
> 博客站点应该被墙了。
> 源码在线看当然不舒服，可以用git把整个站点clone到本地看，每次更新就像其它项目远程协作那样。

github用的不是很溜，我把源码下到本地了，以前的可以在本地看，更新的就在线看好了

**Comment by fanhan-inside** [comment]
> github用的不是很溜，我把源码下到本地了，以前的可以在本地看，更新的就在线看好了

说的就是在线看不舒服，比方说刚更新的剧情暗线备注：

> “<ruby lang="ja">流石<rt>さすが</rt>邦昌<rt>くにまさ</rt>殿<rt>との</rt></ruby>！”

只看「源码」是不是没有浏览器渲染之后的效果呢？

**Comment by CESTBON5146** [comment]
> > github用的不是很溜，我把源码下到本地了，以前的可以在本地看，更新的就在线看好了
> 
> 说的就是在线看不舒服，比方说刚更新的剧情暗线备注：
> 
> > “流石さすが邦昌くにまさ殿との！”
> 
> 只看「源码」是不是没有浏览器渲染之后的效果呢？

只有单纯的文字，没有渲染的效果

**Comment by fanhan-inside** [comment]
> 只有单纯的文字，没有渲染的效果

`<p>“<ruby lang="ja">流石<rt>さすが</rt>邦昌<rt>くにまさ</rt>殿<rt>との</rt></ruby>！”</p>`

你看到的是这种效果么？

**Comment by CESTBON5146** [comment]
> > 只有单纯的文字，没有渲染的效果
> 
> `<p>“<ruby lang="ja">流石<rt>さすが</rt>邦昌<rt>くにまさ</rt>殿<rt>との</rt></ruby>！”</p>`
> 
> 你看到的是这种效果么？
是的，就是这样
<p>洗完澡了精神抖擞容光焕发，上网乱转没发现什么重要情报。那么简单写几句结束本篇注释，把上面出现的剧情提示补充完整。</p>

**Comment by fanhan-inside** [comment]
> 是的，就是这样

那么图片呢？你是怎么在线阅读「源码」的呢？

比方说刚更新了《异闻录》正文〔006〕的脚注，就是一幅应景的政治军事局势图。

只有对照之前之后的素材当中明确声明影射的历史和现实原型，才能理解主要内容和中心思想。更新时间点都是明确的，架空剧情走向与现实一致，源于四十余年来身处迷宫地下城恶人谷对幕后黑手一贯作风的深刻体会，不是市面上充沛的千答万赞事后诸葛亮马后炮碰瓷。

**Comment by CESTBON5146** [comment]
> > 是的，就是这样
> 
> 那么图片呢？你是怎么在线阅读「源码」的呢？
> 
> 比方说刚更新了《异闻录》正文〔006〕的脚注，就是一幅应景的政治军事局势图。
> 
> 只有对照之前之后的素材当中明确声明影射的历史和现实原型，才能理解主要内容和中心思想。更新时间点都是明确的，架空剧情走向与现实一致，源于四十余年来身处迷宫地下城恶人谷对幕后黑手一贯作风的深刻体会，不是市面上充沛的千答万赞事后诸葛亮马后炮碰瓷。
开小飞机看博客成功了，再看一次就行。范队怎么失踪了

**Comment by fanhan-inside** [comment]
> 开小飞机看博客成功了，再看一次就行。范队怎么失踪了

等情报呢。比方说刚在《异闻录》正文〔020〕里面补充脚注。接下来就等南直隶「远东第一体育论坛」的色目竞技爱好者兼《水浒传》《金瓶梅》爱好者爆料了。
