### ISSUE TITLE
把《范版西幻设定集》的幕后黑手称为「厥虐赛斯」怎么样？

### ISSUE THREAD

**Issue by fanhan-inside** [fanhan-inside/fanhan-inside.github.io#48]
简单说，《设定集》是从见得光的人物视角叙述的，正如《异闻录》是从地下工作者视角叙述一样。于是「敌暗我明」的情况下，前者的角色对于幕后黑手的具体情况一无所知，后者则不然。

但是呢，正如漠北大手情报机构指使的岭南精盎情报掮客在向有关部门举报我的个人博客站点之余还在吹捧盎语划时代大作《福尔摩斯》系列的时候，对于钦定主角龙傲天高瞻远瞩算无遗策运筹帷幄决胜千里，在战争迷雾当中处理一团乱麻的线索的时候，毫无根据就能目光如炬一口咬定幕后黑手乃「莫里亚蒂教授」那样，经典反派角色在已经浮出水面但是身份不明的时候，无论是不是集体署名，总要有个帐号用来指代。

所以，《异闻录》反派主角唤作「郭春海」是来自人民群众喜闻乐见的笑话而不是其它任何能揭示国家机密兼宇宙奥秘的线索，在《缘起》当中已经给出理由了。于是照葫芦画瓢，暂时决定运用「扩展ASCII码」当中西欧特色另类字母，拼凑了一个架空名称「“ðøñœçæß”」并根据输入法云反馈音译为「厥虐赛斯」。

这样一来，在已经更新的十七篇正文所涉及的西欧地理范围内，行走于黑暗之中对抗邪恶势力的知晓内幕的角色，就有了一个命名共识，交换情报的时候也不至于各说各话，便于行文表达。今后在市面上搜集到各路情报掮客提供的与反派有关的活动记录，也可以作为素材统一归档。

各位读者以为如何？

**Comment by CESTBON5146** [comment]
说到起名字了，龙空 s1 知乎 4chan 那些外号是怎么起的，有什么渊源吗

**Comment by fanhan-inside** [comment]
> 说到起名字了，龙空 s1 知乎 4chan 那些外号是怎么起的，有什么渊源吗

《[知乎问答№031](https://fanhan-inside.github.io/at_zhihu/qa/031.html)》

**Comment by CESTBON5146** [comment]
生日快乐啊

**Comment by fanhan-inside** [comment]
> 生日快乐啊

谢谢。

刚更新了一段，很快就要提及幕后黑手了，指代标识要写进正文了。意见还是没有征求到……

**Comment by CESTBON5146** [comment]
积累不够所以给不出来意见。
另外幕后黑手应该也是以人的单位存在，那么怎么保持传承和地位呢？像红袍法师们一样吗？

**Comment by fanhan-inside** [comment]
> 积累不够所以给不出来意见。
> 另外幕后黑手应该也是以人的单位存在，那么怎么保持传承和地位呢？像红袍法师们一样吗？

刚更新一段正文，很快就要写到了，暂时可以当成「衍圣公」那么理解。

**Comment by CESTBON5146** [comment]
刚打开知乎 看到推送这个知乎大V曹丰泽据说是满族人，请问是真的吗？ - 寒冰射手曹草草的回答 - 知乎
https://www.zhihu.com/question/357847363/answer/1580837678

**Comment by fanhan-inside** [comment]
> 刚打开知乎 看到推送这个
> 知乎大V曹丰泽据说是满族人，请问是真的吗？ - 寒冰射手曹草草的回答 - 知乎
> https://www.zhihu.com/question/357847363/answer/1580837678

其它回答中有提到其于高考前进行逆向操作「降籍出旗」的，因为判断自己不需要加分也能上清华，至于其「自信」的根本原因没有涉及。用来对比的是同样土木工程专业出身的「高考新附军」马前卒（任冲昊）「抬籍入旗」，然后就上了<del>共济会</del><ins>同济</ins>大学。

不惮以最大的恶意揣测，这是因为2009年7月5日迪化之乱，马前卒跳将出来洗地歪曲为「阶级斗争」，然后在各大宣传阵地遭遇「皇汉」口诛笔伐。于是按照年龄判断（1994年生，2009年刚满15岁，还没有身份证），这位大佐见势不妙赶紧运用人脉修改户部档案。

**Comment by fanhan-inside** [comment]
> 说到起名字了，龙空 s1 知乎 4chan 那些外号是怎么起的，有什么渊源吗

如果说是对宣传阵地的称呼，无一字无来历，基本上都是活跃用户总结出来的言简意赅的形容。

比方说国际化大都市「华语第一精日论坛」评价国际一流和谐宜居之都「低学历废柴社交圈」：

> nga就一中国黄脖子论坛

> 二代论坛，特别是嗷嗷氪金的各个手游板块，“（白泥）从心理学/哲学角度分析明日方舟是我玩过的真左派文学手游”

以后考虑称呼为「兲子脚下首善之区黄脖子二代论坛」了。
