### ISSUE TITLE
邦昌时代，不如叫后满洲国更合适

### ISSUE THREAD

**Issue by marschvor** [fanhan-inside/fanhan-inside.github.io#51]
http://jds.cssn.cn/webpic/web/jdsww/UploadFiles/upload/201011041308124524.pdf

> 工人者，以身命换钱财。故灭之之法，当比商人专加一条，以对内地的工人：工人每日得钱，多少不等，自今以后，当令他们每日捐钱若干。每天得二百文者，值十抽三，捐六十文；每天得二千文者，值十抽三，捐六百文。纳捐的作为官工，不捐的目为私工，与贩卖私盐同罪，就地正法，并当株连募集工人之人，使其不敢收留，以断绝他们的路。如是办法，则他们虽欲不顾身命以求微利，而终不免辗转沟壑之一日矣。

> 自今以后，当使汉人的为农者，不许种米麦，而改种罂粟。种罂粟的故详下结论中。田契地券，旧者作废，须改换新契。换契时，每亩须纳捐若干。不换的把他田地充公。无旧契的，亦把他田地充公。旧契非五十年前者，则把他田地一半充公。五十年前旧契，见经长发贼者，大半失去。

**Comment by fanhan-inside** [comment]
这个说法早已有之，当时九省通衢「军网最黄黄网最军」的消息灵通人士表示，前三十年是「后太平天国」，后三十年才是「后清国」，分界线就是《八二宪法》的制定，留下个特大<ruby>八阿哥<rt lang="en">bug</rt></ruby>，保证国会山是橡皮图章，一切决议都由偏殿军机处说了算。
