### ISSUE TITLE
温家宝与恒大

### ISSUE THREAD

**Issue by marschvor** [fanhan-inside/fanhan-inside.github.io#53]
http://redchinacn.net/forum.php?mod=viewthread&tid=7225

**Comment by fanhan-inside** [comment]
感谢提供情报，墙内看不到，大致能猜出内容。

**Comment by marschvor** [comment]
> 2003年的情况。
> 
> （1）第一大股东情况
> 
> 名称：广州恒大实业集团有限公司成立时间：1996年2月
> 
> 法定代表人：许家印注册资本：3000万元
> 
> 经营范围：国内商业及物资供销业（国家专营专控商品除外），以自有资金投资实
> 
> 业。
> 
> 广州恒大实业集团有限公司控股股东情况介绍：
> 
> 广州恒大实业集团有限公司控股股东为许家印先生（其出资额占该公司总股本的9
> 
> 0%）。
> 
> 许家印，男，1958年出生，中国国籍，大学学历，高级经济师,1997年至今任广州
> 
> 恒大实业集团有限公司党委书记、董事局主席。
> 
> （2）其他持股在10%以上的法人股东
> 
> 名称：海南汉氏环境投资有限公司成立时间：2000年12月
> 
> 法定代表人：温家宏注册资本：5000万元
> 
> 经营范围：城市给排水、环境治理工程投资、施工，环保设备制造、销售，环保新
> 
> 技术开发与应用，环境监测仪器的开发与应用。
> 
> 5、公司前10名流通股股东持股情况表（2003年12月31日）略
看这名字我还以为和人民网论坛差不多，墙内竟然看不到

**Comment by fanhan-inside** [comment]
> 看这名字我还以为和人民网论坛差不多，墙内竟然看不到

非常感谢。墙内连GitHub也是时断时续，这才看见。
